#include "support/TestSignals.h"
#include "io/AudioFile.h"

#include <algorithm>
#include <cmath>
#include <random>

namespace roy::support {

namespace fs = std::filesystem;

namespace {
constexpr double kTwoPi = 6.283185307179586;
}

std::vector<float> testTone(double sr, double freq, double seconds, float amp) {
    std::vector<float> v(static_cast<size_t>(sr * seconds));
    for (size_t i = 0; i < v.size(); ++i) {
        const double t = static_cast<double>(i) / sr;
        const double fade = std::min({1.0, t / 0.02, (seconds - t) / 0.02});
        v[i] = static_cast<float>(amp * std::max(0.0, fade) * std::sin(kTwoPi * freq * t));
    }
    return v;
}

std::vector<float> syntheticVocal(double sr, double seconds) {
    // note (MIDI), detune in cents
    const double notes[][2] = {{57, 0}, {60, 0}, {64, 35}, {62, 0}, {60, 0}, {66, 0}, {64, 0}, {62, -25}, {60, 0}, {57, 0}};
    const int count = 10;
    const double noteLen = seconds / count;
    std::vector<float> v(static_cast<size_t>(sr * seconds));
    double phase = 0;
    for (size_t i = 0; i < v.size(); ++i) {
        const double t = static_cast<double>(i) / sr;
        const int n = std::min(count - 1, static_cast<int>(t / noteLen));
        const double local = t - n * noteLen;
        const double sing = noteLen * 0.82;
        if (local > sing) continue; // short breath between notes
        const double midi = notes[n][0] + notes[n][1] / 100.0;
        const double f = 440.0 * std::pow(2.0, (midi - 69.0) / 12.0) * (1.0 + 0.005 * std::sin(kTwoPi * 5.3 * t));
        phase += kTwoPi * f / sr;
        const double env = std::min(1.0, local / 0.04) * std::min(1.0, (sing - local) / 0.08);
        double s = 0;
        for (int h = 1; h <= 14; ++h) {
            const double fh = f * h;
            const double formant = std::exp(-std::pow((fh - 650) / 160, 2)) + 0.7 * std::exp(-std::pow((fh - 1150) / 190, 2)) +
                                   0.25 * std::exp(-std::pow((fh - 2600) / 300, 2)) + 0.04;
            s += formant * std::sin(phase * h) / h;
        }
        v[i] = static_cast<float>(0.4 * env * s);
    }
    return v;
}

std::vector<float> drumHit(const std::string& kind, double sr) {
    std::mt19937 rng(7);
    std::uniform_real_distribution<float> noise(-1.0f, 1.0f);
    const double len = kind == "808" ? 1.6 : kind == "kick" ? 0.5 : kind == "openhat" ? 0.45 : kind == "hat" ? 0.08 : 0.3;
    std::vector<float> v(static_cast<size_t>(sr * len));
    double phase = 0;
    float lp = 0;
    for (size_t i = 0; i < v.size(); ++i) {
        const double t = static_cast<double>(i) / sr;
        double s = 0;
        if (kind == "kick") {
            const double f = 45.0 + 110.0 * std::exp(-t * 30.0);
            phase += kTwoPi * f / sr;
            s = std::sin(phase) * std::exp(-t * 7.0) + 0.3 * noise(rng) * std::exp(-t * 200.0);
        } else if (kind == "808") {
            const double f = 55.0 * (1.0 + 0.6 * std::exp(-t * 25.0)); // A1 with a short pitch drop
            phase += kTwoPi * f / sr;
            s = std::tanh(1.6 * std::sin(phase)) * std::exp(-t * 1.6) * std::min(1.0, t / 0.002);
        } else if (kind == "snare") {
            phase += kTwoPi * 190.0 / sr;
            s = 0.5 * std::sin(phase) * std::exp(-t * 25.0) + 0.6 * noise(rng) * std::exp(-t * 14.0);
        } else if (kind == "clap") {
            const double burst = (t < 0.03 && std::fmod(t, 0.01) < 0.004) ? 1.0 : std::exp(-(t - 0.03) * 18.0) * (t >= 0.03);
            s = 0.7 * noise(rng) * burst;
        } else { // hats: high-passed noise
            const float n = noise(rng);
            lp += 0.35f * (n - lp);
            s = (n - lp) * std::exp(-t * (kind == "openhat" ? 7.0 : 60.0)) * 0.6;
        }
        v[i] = static_cast<float>(std::clamp(s * 0.8, -1.0, 1.0));
    }
    return v;
}

std::vector<std::string> writeTestSignals(const fs::path& folder, std::string* error) {
    const double sr = 48000.0;
    std::vector<std::string> written;
    auto write = [&](const fs::path& rel, const std::vector<float>& mono, bool stereo) {
        const fs::path p = folder / rel;
        std::error_code ec;
        fs::create_directories(p.parent_path(), ec);
        fs::remove(p, ec); // test kit files are always regenerated by us
        std::vector<std::vector<float>> ch = stereo ? std::vector<std::vector<float>>{mono, mono} : std::vector<std::vector<float>>{mono};
        std::string err;
        if (writeWavFile(p, ch, sr, SampleFormat::Pcm24, false, &err)) written.push_back(rel.generic_string());
        else if (error) *error = err;
    };
    write("Audio/Test_Tone_440Hz_-12dBFS.wav", testTone(sr, 440.0, 5.0), true);
    write("Audio/Test_Tone_1kHz_-12dBFS.wav", testTone(sr, 1000.0, 5.0), true);
    write("Audio/Synthetic_Vocal_A_minor_with_off_key_notes.wav", syntheticVocal(sr, 8.0), false);
    for (const char* k : {"kick", "snare", "clap", "hat", "openhat", "808"})
        write(fs::path("Samples/Drums") / (std::string("RoY_Test_") + k + ".wav"), drumHit(k, sr), false);
    return written;
}

} // namespace roy::support
